### PR TITLE
Finish webapp

### PR DESCRIPTION
**Pull request by NormalDuck**
This pull request has a working production build in my fork and adds manual page, fixes leaderboard, browser issues and most eslint errors

The visuals are still quite ugly and doesn't have a pleasant user experience

### CODE REVIEW

**Comment by NormalDuck** [comment]
Issues mentioned in https://github.com/XBOT-FTC/FTC-Scouting-App/issues/61 https://github.com/XBOT-FTC/FTC-Scouting-App/issues/59 are not resolved in this pull request

**Review by johnylamw — CHANGES_REQUESTED** [review]
Issues:
- Leaderboard not showing when filtered by "minimum". All entries are 0 when trying to view the minimum scores.
- No navigation bar to return to the dashboard page without having to input the name again. Perhaps cache the name so that you don't need to re-enter it each time. Also, is it easy to update the schema and database with the scouter's name? Just in case we want to know who scouted which match.
- Add checks to be sure that a match number and team name is selected before they can "continue". At the moment, it sends to the drafting page even if you have nothing selected which results in an assertion error when trying to submit the data.

If possible, for viewing a specific team's information (under /details), when looking at the different matches they played in, can you **bold** the row for that **specific** team that they played in for visual clarity? Or are some sort of highlighting? That way the person viewing the data can immediately find which team they are currently looking at.

Extra features that you can add if you have time and want to:
- Add a way to like grey out teams on the leaderboard which allows the alliance captain of our team to like 'filter' teams out of the list (or make it visually less known). The purpose of it is 1. that team is unable to form an alliance with (meaning they already have their own alliance) and 2. the particular team "too terrible" to be paired up with and not worth looking at. 
- Pigging back off of the previous request, you can perhaps add like a "priority" system which lets the captain select which teams have "higher" priority which will automatically sort it to the top of the list so that they can keep track of the teams they have selected. Basically an "add to favorite" button.
- Details page:
 - **IMPORTANT** We need to display driver's comment in the details page so that our captain knows what concerns/comments people have about the robot. Additionally, we're missing a lot of other data such as driver's rating, fouls, how many specimans/samples they scored in auto, teleop.. low or high.. etc It would be important to be able to see these specific stats. If this is too much for you, can you just add like a "raw" view of the json data listed on mongodb (but definitely apply so small preprocessing to it to filter out only data from that specific team)?.
 - Can you sort the list by color rather than team # so it's easier to see who was on which team.
 - Also add like a "general" statistics of their overall stats like how you have it listed in leaderboards page just to make the user experience better.

**Comment by NormalDuck** [comment]
> Leaderboard not showing when filtered by "minimum". All entries are 0 when trying to view the minimum scores.

No data is shown when you select `minimum` filter is intentional. Because this filter finds the lowest score, and we didn't finish scouting **all** the matches. So all team's minimum score is expected to be 0  

---

> No navigation bar to return to the dashboard page without having to input the name again.

Mentioned in the github issue. Will fix it in the next pull request

---

> Add checks to be sure that a match number and team name is selected before they can "continue".

 Will fix that in this pull request

**Comment by johnylamw** [comment]
A minor concern is the way you're calculating the data in the "leaderboards" page in which you take the average of all the matches including the matches that aren't scouted yet (which are left as zeros in the data). However, this wouldn't be an accurate representation of the robot's capabilities if our drive team is using it during the qualification matches to measure the strength of their team and the opponent team.

Ex: Only 1 match is played where 3231 scored 6 specimens, however, since there are 5 more matches to be played, the average computes to one 1 specimen which significantly weakens the view that 3231 can score 6 specimens per match. This might devalue who we view other teams in coming up with a strategy during the game.

Are you able to compute the calculations based on the matches scouted? You can either sort through the list and add up all the instances of 'scouted' or store a separate data in TeamProperties that you can update after every scouted match.

**Comment by johnylamw** [comment]
> > Leaderboard not showing when filtered by "minimum". All entries are 0 when trying to view the minimum scores.
> 
> No data is shown when you select `minimum` filter is intentional. Because this filter finds the lowest score, and we didn't finish scouting **all** the matches. So all team's minimum score is expected to be 0
> 

Are you filtering by the lowest score of a given match or overall "lowest" score?

**Comment by NormalDuck** [comment]
> Are you able to compute the calculations based on the matches scouted? 

Yes, thats possible. I have a field called `scouted`. I can choose to ignore the unscouted matches to make the average less polluted during qualification matches

**Comment by johnylamw** [comment]
Oh right, nevermind. I got confused for a second on the maximum and minimum thingy..

**Comment by johnylamw** [comment]
Great work though! Good to see the scouting app getting put together. I might have more requests that needs to be added but I'll need to think about it.

**Comment by johnylamw** [comment]
I'm happy to approve this once you address the match selection continue issue then you can work on another PR so it doesn't get too messy.

**Review by johnylamw — CHANGES_REQUESTED** [review]
Averaging logic looks good now. Great work on that.

However, problem still persist with the continue button (you can click on the text directly rather than the button) and button is still locked out even if you have the two fields selected unless it's an issue on my end.

**Comment by johnylamw** [comment]
Also, if you return to the alliance page (by clicking on the home icon), the state of the select is preserved (underlying logic) even though the text is reverted back to the original "Match Number" and "Team Number"


-

Probably need to add some onChange to flush it out and perhaps add some conditions to <Link href={"/auto"}> Continue</Link> for it to not route to /auto if nothing is selected. For example, link to /auto only if there is a cursor and match number, otherwise, it only routes to itself? There are other ways you can do it though

**Comment by NormalDuck** [comment]
@johnylamw The issue has been fixed

**Review by johnylamw — APPROVED** [review]
Happy with the changes, however, there is still one more small issue:

Currently, Match 1 is fully scouted, which prevents you from being able to select any of robots (good job on this check btw). However, if you select Match 2, and pick any of the robot from the list, and then switch back to Match 1, it allows you to scout the same robot on whichever index you picked from Match 2 for Match 1 instead. Could you do place an extra check to make sure that match numbers that are fully scouted cannot be selected from the list? (greyed out to indicate it's already scouted or remove it from the drop down, whichever is easier), this feature is also good as an indicator to scouters on which match they should be on when they reload the page.

Apologies for hitting you with so changes. Just pretend you're interning at Microsoft and I'm your manager and we need to get this product shipped out in a week! 

Nonetheless, great work on the delivery of the changes :+1: 

I'm going to approve this for now, but make sure to address the issue in another PR when you can or now if you want to :)

**Comment by NormalDuck** [comment]
I have been noticing the glitch/bug you have addressed. I couldn't find a solution to it so I gave up since I can assume scouters wont sabotage that bug to mess up the data hopefully

**Pull request merged**
