### PR TITLE
add rng game and fix issues

### PR DESCRIPTION
**Pull request by NormalDuck**
image
very fun game

solves
https://github.com/XBOT-FTC/FTC-Scouting-App/issues/35
and adds the schema for end phase.

### CODE REVIEW

**Comment by NormalDuck** [comment]
https://github.com/user-attachments/assets/8e162dd7-1e25-480c-9926-c342aece7837

very good preview of the functionality 👍

**Review by johnylamw — CHANGES_REQUESTED** [review]
Great feature! Exactly what we needed for a scouting app! However... How do I exit the RNG screen afterwards?

**Comment by NormalDuck** [comment]
You don't exit! you show the number to the next person thats scouting! If I make a exit feature, then someone might sabotage the scouter and make them redo the RNG game which makes things not fair.

**Comment by johnylamw** [comment]
Perhaps change the RNG to happen every x matches rather than after every match (and create an admin panel that lets us disable this option and adjust the parameters) - Scouts usually work in block schedules so it's not like we switch scouts after every match. In FRC, they usually scout 5 matches before moving onto the next person. OR if we can convince the team of scouters to always be on their toes, then this could work but I'd imagine it'll be super stressful for everyone to find the next randomized person after every single match. But for the fun of it, it can just be a game of tag between the previous scouter and next scouter. We also want a way to exclude certain people from being randomized with a click of a button in case they're busy making repairs and software changes for the robot.

For perspective, we will run through like 25 matches during the district meets and around 40ish for district championships.

It would also be nice to make it so they can exit the RNG screen because the internet may be too slow and reloading a page might be :skull:

If you want to make it fair, you can setup a slack channel for a bot to announce who is next so that they can't change the result from the 1st generation :)

I like the idea of RNG though!

**Comment by johnylamw** [comment]
All in all, we can ask the team if they're a fan of the idea!

**Comment by NormalDuck** [comment]
> they usually scout 5 matches before moving onto the next person
Since we will be scouting 5 matches per person, it means that around ~14 people will scout, leaving some people not being able to scout at all. To ensure true fairness switching the person after each match can make it so much more equal than 5 matches then switching to the next person.

**Comment by johnylamw** [comment]
5 is a number for FRC where the matches are played more quickly and spans over 2 days with about ~75 qualifications matches. For FTC, it is indeed smaller so this a smaller number would work. We just want it to be arbitrary so that we can adapt on the fly if there turns out to be shortage of scouters on the day of the matches.

Also, don't forget there's 4 teams per match so we need a total of 4 x 25 scout entries. Meaning 100 entries total (1 for each team) and having Scouts rotate after 5 matches still ensures there is enough scouting to do for 20 people.

However, we don't need to do this if all the students agree w/ the approach of randomizing after each match (if you can accommodate that it doesn't generate the same number twice)

**Pull request merged**
